name: Fichaje automatico Ficha.Work

on:
  workflow_dispatch:

jobs:
  fichar:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el codigo del repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Ejecutar el script de fichaje
        env:
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
        run: node fichawork.js
