name: Fichaje automatico Ficha.Work

on:
  schedule:
    - cron: '0 5 * * 1-5'   # 08:00 UTC -> 09:00 hora Madrid (con UTC+1) / 10:00 (con UTC+2)
    - cron: '30 13 * * 1-5'  # 16:00 UTC -> 17:00 hora Madrid (con UTC+1) / 18:00 (con UTC+2)
  workflow_dispatch:

jobs:
  fichar:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el codigo del repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Ejecutar el script de fichaje
        env:
          USER: ${{ secrets.USER }}
          PASS: ${{ secrets.PASS }}
        run: node fichawork.js
